# Generated by Django 5.0.7 on 2024-08-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCardHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_cover', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_workflow', models.CharField(blank=True, max_length=250, null=True)),
                ('photo_flag', models.CharField(blank=True, max_length=250, null=True)),
                ('location_link', models.CharField(blank=True, max_length=250, null=True)),
                ('photo_weather', models.CharField(blank=True, max_length=250, null=True)),
                ('ocr_workflow', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
