# Generated by Django 5.0.7 on 2024-08-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcardheaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardheader',
            name='photo_polaroid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
