# Generated by Django 5.0.7 on 2024-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ocr_workflow',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
